### ISSUE TITLE
Create Binary Distributions

### ISSUE THREAD

**Issue by mh-northlander** [WorksApplications/sudachi.rs#104]

**Comment by eiennohito** [comment]
1. Binary build should use PGO: https://doc.rust-lang.org/rustc/profile-guided-optimization.html
2. What Python versions we are going to cover? 3.6+? https://endoflife.date/python Should we consult with GinZa for this? @hiroshi-matsuda-rit
3. What platforms should we build binaries? Building for Linux is easy-ish (https://github.com/pypa/manylinux). See also https://github.com/marketplace/actions/python-wheels-manylinux-build (or other Google results).  For Windows/maxOS I am not sure.

**Comment by eiennohito** [comment]
For PGO we can't use available actions because we have to invoke `python setup.py` in a special manner (with RUSTFLAGS environment variable)

**Comment by eiennohito** [comment]
Current plan is to build binaries for 
Python versions: 3.6, 3.7, 3.8. 3.9 and 3.10 
OS: Linux (with manylinux containers), Windows, macOS
Linux - do only x86_64 builds with PGO
Windows - do only x86_64 builds without PGO (or maybe with if it will be easy)
macOS - do universal x86_64/Aarch64 builds (!) without PGO (or similarily to Windows)
