### ISSUE TITLE
change python package name

### ISSUE THREAD

**Issue by mh-northlander** [WorksApplications/sudachi.rs#121]
`sudachi` to `SudachiPy`

**Comment by eiennohito** [comment]
Really need to check that this will not break installing a dictionary package from pip (which depend on SudachiPy package)

**Comment by mh-northlander** [comment]
sudachidict requires SudachiPy~=0.5.0:
https://github.com/WorksApplications/SudachiDict/blob/aa7a16ec2ca8f05c423edcd5e4b17b5a6607c88c/python/setup.py#L69

We need to update this.

**Comment by mh-northlander** [comment]
https://github.com/WorksApplications/SudachiDict/pull/37
