### ISSUE TITLE
Automate version management

### ISSUE THREAD

**Issue by mh-northlander** [WorksApplications/sudachi.rs#128]
Updating the version of all of rust/python/etc. is too hard for human.

**Comment by eiennohito** [comment]
Having a script which replaces versions would be good.

Having to specify both current and new version would be foolproof as well (at least compared to specifying only new version)

**Comment by mh-northlander** [comment]
Rust follows [semantic versioning](https://semver.org/) (https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field).
Python's versioning rule defined in [PEP 440](https://www.python.org/dev/peps/pep-0440/)

The format [MAJOR.MINOR.PATCH-PRERELEASE] will be accepted by both of them, although the normalization of python side will remove "-" before pre-release part (https://www.python.org/dev/peps/pep-0440/#pre-release-separators).

**Comment by mh-northlander** [comment]
Files which has a version section:
- `Cargo.toml` of `sudachi`, `sudachi-cli`, `plugin`s (4 in total), and `python`
- `python/setup.py`
  - `__version__` will be set automatically in `sudachipy/__init__.py`
- `python/docs/source/conf.py`
- `README.md`s
