### ISSUE TITLE
Add build-dictionary mode

### ISSUE THREAD

**Issue by mh-northlander** [WorksApplications/sudachi.rs#13]
Current sudachi.rs cannot build both system and user dictionary.
We want to a cli tool for that feature as java/python

We can still use dictionaries build by java/python version

**Comment by eiennohito** [comment]
Need to list up features for dictionary format change.

**Comment by eiennohito** [comment]
Changing dictionary format is out of scope at the moment, should produce dictionaries that are compatible with Java version
