### ISSUE TITLE
Change the way to load __version__

### ISSUE THREAD

**Issue by mh-northlander** [WorksApplications/sudachi.rs#139]
https://github.com/WorksApplications/sudachi.rs/blob/d189b0e5d577441920c077ed797ff9d77de6a95e/python/py_src/sudachipy/__init__.py#L12-L19

[importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html) is supported from python 3.8.

**Comment by eiennohito** [comment]
Simply hardcode it in `__init__.py` and add to the update the version update script.
