### ISSUE TITLE
Keep default mode after tokenize

### ISSUE THREAD

**Issue by mh-northlander** [WorksApplications/sudachi.rs#148]
The mode provided to `Tokenizer.tokenize` should not overwrite the default mode.

https://github.com/WorksApplications/sudachi.rs/blob/ad1f15818536a379c668ea48fcebaca2278df38e/python/src/tokenizer.rs#L103

**Comment by eiennohito** [comment]
Nice catch. `set_mode` returns the previous mode, so this is easily fixable by calling `set_mode` once more after getting the MorphemeList from tokenizer.

I'm not sure it is the best API decision to pass mode with every tokenization request though.
