### ISSUE TITLE
Reorganize source code

### ISSUE THREAD

**Issue by eiennohito** [WorksApplications/sudachi.rs#16]
Proposal for reorganization:

* main folder: sudachi crate (rlib), does not produce binary, is library only
* sudachi-cli folder: sudachi-cli (bin), produces sudachi executable
* python: python bindings (cdylib), #25 
* plugins: contains individual plugins (cdylib) (for testing only, core plugins: #17)

Other nice things to have: API usage examples

**Comment by mh-northlander** [comment]
FYI: [lindera](https://github.com/lindera-morphology/lindera), kuromoji-based tokenizer. ([article by the author](https://qiita.com/mosuka/items/0fdaaf91f5530d427dc7#lindera))
