### ISSUE TITLE
Documentation for the tagset used by the POS tagger of Sudachi

### ISSUE THREAD

**Issue by BLKSerene** [WorksApplications/sudachi.rs#199]
Hi, I'm wondering that if there are any documentation for the tagset used by the POS tagger of Sudachi?

**Comment by kazuma-t** [comment]
See the following thread on Slack.
https://sudachi-dev.slack.com/archives/CBCF278AC/p1617584539086100

**Comment by BLKSerene** [comment]
Thanks, but neither the pdf link nor the Python code snippet works now.

**Comment by eiennohito** [comment]
If you are using 0.6.2, the following snippet should work

```python
import sudachipy
sudachi_dic = sudachipy.Dictionary()
matcher = sudachi_dic.pos_matcher([()])
for pos_id, pos in enumerate(matcher):
  print(pos_id, ",".join(pos), sep="\t")
```

**Comment by kazuma-t** [comment]
It seems that the BCCWJ manual has been moved here.
https://ccd.ninjal.ac.jp/bccwj/doc/manual/BCCWJ_Manual_05.pdf

**Comment by BLKSerene** [comment]
Thanks!
