### ISSUE TITLE
POS tagging a list of tokens which have already been tokenized

### ISSUE THREAD

**Issue by BLKSerene** [WorksApplications/sudachi.rs#200]
Hi, are there any way to POS-tag a list of token which have already been tokenized (by SudachiPy or other tokenizers)?

**Comment by eiennohito** [comment]
Currently there is no way to perform partial analysis

**Comment by kazuma-t** [comment]
MeCab is capable of constrained tokenization (partial analysis). 
https://taku910.github.io/mecab/partial.html

Sudachi does not provide this feature because the plugins rewrite the analysis results.

**Comment by BLKSerene** [comment]
Thanks. Got it.
