### ISSUE TITLE
READMEの手順不備？

### ISSUE THREAD

**Issue by microwavePC** [WorksApplications/sudachi.rs#208]
1. README上に記載されている以下のコマンドは、正しくは「pip install --upgrade 'sudachipy>=0.6.2'」ではないでしょうか？
> pip install --update 'sudachipy>=0.6.2'

2. 以下のコマンドが通りません。エラー「error: found a virtual manifest at `/(略)/sudachi.rs/Cargo.toml` instead of a package manifest」となります。
> cargo install --path .

**Comment by microwavePC** [comment]
> 以下のコマンドが通りません。エラー「error: found a virtual manifest at /(略)/sudachi.rs/Cargo.toml instead of a package manifest」となります。

Cargo.tomlにpackageセクションが入っていないために発生しているように見えます。

**Comment by mh-northlander** [comment]
For 2., please try `cargo install --path sudachi-cli/` instead.
