### ISSUE TITLE
Update SplitMode implementation

### ISSUE THREAD

**Issue by mh-northlander** [WorksApplications/sudachi.rs#243]
The issue around enum on PyO3 side seems solved: https://github.com/PyO3/pyo3/issues/834.
https://github.com/WorksApplications/sudachi.rs/blob/d09dd0079b48cd307626b7a4a350deddd52ea132/python/src/tokenizer.rs#L38-L39

Check if we can use it for the PySplitMode.

**Comment by eiennohito** [comment]
Probably should also accept string literals, `"A"`, `"B"`, `"C"` as well.
