### ISSUE TITLE
Update PyO3 to 0.21

### ISSUE THREAD

**Issue by mh-northlander** [WorksApplications/sudachi.rs#254]
There are large API changes in [PyO3 0.21](https://github.com/PyO3/pyo3/releases#:~:text=Compare-,PyO3%200.21.0,-This%20release%20introduces) (current implementation will be deprecated from 0.23).

Update following [the migration guide](https://pyo3.rs/v0.21.0/migration.html)

**Comment by apmorton** [comment]
pyo3 v0.22 is the minimum that supports python 3.13 - any chance you can bump to that version?

See: https://github.com/conda-forge/sudachipy-feedstock/pull/1
