### ISSUE TITLE
Getting the pronunciation of a lemma

### ISSUE THREAD

**Issue by evertedsphere** [WorksApplications/sudachi.rs#269]
Is there a way to get a reading for the lemma underlying a given morpheme, in the way that the 終止形/spelling of the lemma is available via `dictionary_form()`? 

I believe the Sudachi dictionaries are based upon UniDic, so a way to get a UniDic ID/GUID would also be useful if that information happens to be stored in the dictionary. (Perhaps `dictionary_form_word_id` might be of use?)

**Comment by mh-northlander** [comment]
Currently we don't have a sophisticated way for that.
If you are using rust version, you can use following (maybe need to adjust borrowing etc.):
```rust
let dfwi = WordId::new(morpheme.dictionary_id(), morpheme.get_word_info().dictionary_form_word_id()));
let dictionary_form_reading = dictionary.lexicon().get_word_info(dfwi)?.reading_form();
```

For python, you may use `dictionary.lookup` method.
But in python version we don't have access to `dictionary_form_word_id` (in non-deprecated way) and cannot select correct one from candidates.
```python
candidates = dictionary.lookup(morpheme.dictionary_form())
dictionary_form_reading = candidates[0].reading_form()  # can be incorrect or index-out-of-range
```

We are now considering entire API rework, and may add a better way for this.

About UniDic, words are ported into Sudachi dictionary but they are not in superset/subset relation. Probably we won't provide that kind of information.

**Comment by evertedsphere** [comment]
Thanks, that makes sense. Is there an issue tracking the API rework initiative?

**Comment by mh-northlander** [comment]
It is currently our company internal and not opened yet.

**Comment by evertedsphere** [comment]
@mh-northlander how can this feature be used now? I'm using the Python API.

**Comment by evertedsphere** [comment]
@mh-northlander I see you've marked this issue as completed, but it's not clear to me what the solution is. Could you explain, or perhaps point me to a commit or a section of the code that allows the user to do this?

**Comment by mh-northlander** [comment]
@evertedsphere 
Currently (sudachipy v0.6.10) the above code should work.

API rework is still in progress in Java version (https://github.com/WorksApplications/Sudachi/milestone/3). We will sync rust/python API after Java version is updated.
We will hide dictionary_form_word_id, and instead enable to access dictionary_form morpheme (https://github.com/WorksApplications/Sudachi/issues/265).

**Comment by evertedsphere** [comment]
> Currently (sudachipy v0.6.10) the above code should work.

I believe this limitation is still there with the Python code shown above:

> `# can be incorrect or index-out-of-range`

since it picks a candidate at (essentially) random.

```py
candidates = DICTIONARY.lookup(tok.lemma_)
dfrs = [c.reading_form() for c in candidates]
print(f"{dfrs}")
```
for `開く` produces
```
['アク', 'ヒラク', 'アク', 'ヒラク']
```

This _can_ be hacked around using the surface form reading and seeing which form has the longest common prefix with it.
```py
class SzrJapaneseTokenizer(spacy.lang.ja.JapaneseTokenizer):
    def __call__(self, text: str) -> Doc:
        doc = super().__call__(text)
        for tok in doc:
            morph = tok.morph.to_dict()
            candidates = DICTIONARY.lookup(tok.lemma_)
            dfrs = [c.reading_form() for c in candidates]
            dfr = longest_common_prefix(morph['Reading'], dfrs)
            morph["LemmaReading"] = dfr
            tok.morph = MorphAnalysis(self.vocab, morph)
        return doc
```
which is fine for the time being.

For my application, keeping all of the morphological analysis code in Python would be convenient, so I'm interested in when support for that will land.
