### ISSUE TITLE
Remove lifetime parameter from Morpheme

### ISSUE THREAD

**Issue by mh-northlander** [WorksApplications/sudachi.rs#43]
To use `Morpheme` in the python binding (#25), we need to remove lifetime parameter from it.

**Comment by eiennohito** [comment]
Python API needs its own Morpheme, copying the needed data from the internal one.
Python API morpheme should be able to outlive the analysis of the individual sentence -> it can't have references to the analysis state. It can have pointer (Arc) to the grammar though.

**Comment by mh-northlander** [comment]
Having `Arc<Grammar>` will have a same lifetime parameter problem. I'll use dictionary instead for now
