### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by tmfink** [WorksApplications/sudachi.rs#6]
This project has no license, which means (by default) users do not have rights to use it.

Fix steps:
- [x] Add license file to repo
    - https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository
- [x] Add "license" field to `Cargo.toml`
    - https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields

I suggest Apache 2.0 license [like Sudachi](https://github.com/WorksApplications/Sudachi/blob/develop/LICENSE-2.0.txt).

**Comment by tmfink** [comment]
@sorami Thanks for your awesome crate--it's exactly what I was looking for.
Having a license will make users much more willing to use your crate.  :smile:

**Comment by tmfink** [comment]
Thanks!

**Comment by sorami** [comment]
@tmfink 

Hi, thanks for the suggestion! I have set the license to Apache 2.0.

Also, just to let you know that this is my hobby project to practice Rust, and this library has an fatal problem (throws an error) when an Out-of-Vocabulary is in the text. I have added the caution to the README.

Also have a look at an alternative by another person, https://github.com/Yasu-umi/sudachiclone-rs (this one is registerd to crates.io).

**Comment by tmfink** [comment]
@sorami No worries--hobby projects can be useful. I'm looking at using this crate in my hobby project to tag Japanese text with furigana. With Rust's error handling, it will be easy to gracefully handle errors (at least avoid a panic).

I have taken a looked at sudachiclone-rs and even made a [pull request](https://github.com/Yasu-umi/sudachiclone-rs/pull/7).
