### ISSUE TITLE
Disable dictionary version check

### ISSUE THREAD

**Issue by hata6502** [WorksApplications/sudachi.rs#8]
The dictionary version check: `src/dic/header.rs line 17` may be not needed.

```rust
        assert_eq!(header.version, 0x7366d3f18bd111e7);

```

## Reason

When I use `sudachi-dictionary-20210608-core.zip`, the built `sudachi` command failed. 

```bash
$ echo "あ" | sudachi
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `14888620106744153140`,
 right: `8315566796372513255`', src/dic/header.rs:17:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

When I discommented `src/dic/header.rs line 17`,

```rust
        //assert_eq!(header.version, 0x7366d3f18bd111e7);

```

the rebuilt `sudachi` command run successfully. 

```bash
$ echo "あ" | sudachi
あ	感動詞,フィラー,*,*,*,*	あー
EOS

```

**Comment by mh-northlander** [comment]
This is due to the dictionary structure change in [v20201223](https://github.com/WorksApplications/SudachiDict/releases/tag/v20201223).

**Comment by mh-northlander** [comment]
Now header version check is implemented and we can use any system dictionary.
